# Generated by Django 5.2.8 on 2025-11-17 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("et_number", models.CharField(max_length=50, unique=True)),
                ("student_phone_number", models.CharField(max_length=15)),
                ("father_name", models.CharField(max_length=100)),
                ("father_phone_number", models.CharField(max_length=15)),
                (
                    "student_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "fees_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("utr_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pending_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("room_type", models.CharField(max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
