# Generated by Django 5.2.8 on 2025-11-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("et_number", models.CharField(max_length=50, unique=True)),
                ("student_phone_number", models.CharField(max_length=15)),
                ("father_name", models.CharField(max_length=100)),
                ("father_phone_number", models.CharField(max_length=15)),
                (
                    "fees_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("utr_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pending_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Room"),
                            ("AC", "AC Room"),
                            ("DELUXE", "Deluxe Room"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
