# Generated by Django 5.2.8 on 2025-11-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="room_type",
            field=models.CharField(max_length=50),
        ),
    ]
