# Generated by Django 5.2.8 on 2025-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_image",
            field=models.ImageField(blank=True, null=True, upload_to="student_images/"),
        ),
    ]
