# Generated by Django 5.2.8 on 2025-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_is_verified_alter_student_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_email",
            field=models.EmailField(
                default="babuballa90@gmail.comexit", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
