# Generated by Django 5.2.8 on 2025-11-17 10:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_is_verified_alter_student_room_type"),
    ]

    operations = [
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql="SELECT 1;"
        ),
    ]
