# Generated by Django 5.2.8 on 2025-11-17 18:09

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="student_images/",
            ),
        ),
    ]
