# Generated by Django 5.2.8 on 2025-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_dailymeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymeal",
            name="breakfast_scanned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailymeal",
            name="dinner_scanned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailymeal",
            name="lunch_scanned",
            field=models.BooleanField(default=False),
        ),
    ]
