# Generated by Django 5.2.8 on 2025-11-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("office", "Office Staff"),
                    ("accounts", "Accounts"),
                    ("warden", "Warden"),
                    ("kitchen", "Kitchen"),
                    ("staff", "Staff"),
                ],
                max_length=20,
            ),
        ),
    ]
