# Generated by Django 5.2.8 on 2025-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_staffrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymeal",
            name="manual_present",
            field=models.BooleanField(default=False),
        ),
    ]
